/*
 * Copyright 2025-2026 @NightMean (https://github.com/NightMean)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ollitert.llm.server.ui.server

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.compose.LifecycleEventEffect
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.ollitert.llm.server.R
import com.ollitert.llm.server.common.ServerStatus
import com.ollitert.llm.server.data.prefs.UI_TIMER_TICK_MS
import com.ollitert.llm.server.data.prefs.formatHostForUrl
import com.ollitert.llm.server.ui.common.SCREEN_CONTENT_MAX_WIDTH
import kotlinx.coroutines.delay
import java.util.Locale

@Composable
fun StatusScreen(
  serverViewModel: ServerViewModel,
  onReloadModel: () -> Unit,
  modifier: Modifier = Modifier,
) {
  val status by serverViewModel.status.collectAsStateWithLifecycle()
  val modelName by serverViewModel.activeModelName.collectAsStateWithLifecycle()
  val modelSizeBytes by serverViewModel.activeModelSize.collectAsStateWithLifecycle()
  val port by serverViewModel.port.collectAsStateWithLifecycle()
  val bindAddress by serverViewModel.bindAddress.collectAsStateWithLifecycle()
  val isLoopbackOnly by serverViewModel.isLoopbackOnly.collectAsStateWithLifecycle()
  val startedAtMs by serverViewModel.startedAtMs.collectAsStateWithLifecycle()
  val requestCount by serverViewModel.requestCount.collectAsStateWithLifecycle()
  val tokensGenerated by serverViewModel.tokensGenerated.collectAsStateWithLifecycle()
  val tokensIn by serverViewModel.tokensIn.collectAsStateWithLifecycle()
  val lastLatencyMs by serverViewModel.lastLatencyMs.collectAsStateWithLifecycle()
  val peakLatencyMs by serverViewModel.peakLatencyMs.collectAsStateWithLifecycle()
  val avgLatencyMs by serverViewModel.avgLatencyMs.collectAsStateWithLifecycle()
  val textRequests by serverViewModel.textRequests.collectAsStateWithLifecycle()
  val imageRequests by serverViewModel.imageRequests.collectAsStateWithLifecycle()
  val audioRequests by serverViewModel.audioRequests.collectAsStateWithLifecycle()
  val errorCount by serverViewModel.errorCount.collectAsStateWithLifecycle()
  val lastTtfbMs by serverViewModel.lastTtfbMs.collectAsStateWithLifecycle()
  val avgTtfbMs by serverViewModel.avgTtfbMs.collectAsStateWithLifecycle()
  val lastDecodeSpeed by serverViewModel.lastDecodeSpeed.collectAsStateWithLifecycle()
  val peakDecodeSpeed by serverViewModel.peakDecodeSpeed.collectAsStateWithLifecycle()
  val lastPrefillSpeed by serverViewModel.lastPrefillSpeed.collectAsStateWithLifecycle()
  val lastItlMs by serverViewModel.lastItlMs.collectAsStateWithLifecycle()
  val activeAccelerator by serverViewModel.activeAccelerator.collectAsStateWithLifecycle()
  val thinkingEnabled by serverViewModel.thinkingEnabled.collectAsStateWithLifecycle()
  val speculativeDecodingEnabled by serverViewModel.speculativeDecodingEnabled.collectAsStateWithLifecycle()
  val modelLoadTimeMs by serverViewModel.modelLoadTimeMs.collectAsStateWithLifecycle()
  val isIdleUnloaded by serverViewModel.isIdleUnloaded.collectAsStateWithLifecycle()
  val loadingStartedAtMs by serverViewModel.loadingStartedAtMs.collectAsStateWithLifecycle()
  val lastError by serverViewModel.lastError.collectAsStateWithLifecycle()

  val isStopped = status == ServerStatus.STOPPED

  // Live uptime ticker
  var uptimeSeconds by remember { mutableLongStateOf(0L) }
  LaunchedEffect(startedAtMs, status) {
    if (status == ServerStatus.RUNNING && startedAtMs > 0) {
      while (true) {
        uptimeSeconds = (System.currentTimeMillis() - startedAtMs) / 1000
        delay(UI_TIMER_TICK_MS)
      }
    } else {
      uptimeSeconds = 0L
    }
  }

  var loadingElapsedSeconds by remember { mutableLongStateOf(0L) }
  LaunchedEffect(loadingStartedAtMs) {
    if (loadingStartedAtMs > 0) {
      while (true) {
        loadingElapsedSeconds = (System.currentTimeMillis() - loadingStartedAtMs) / 1000
        delay(UI_TIMER_TICK_MS)
      }
    } else {
      loadingElapsedSeconds = 0L
    }
  }

  val context = LocalContext.current

  var authOn by remember { mutableStateOf(serverViewModel.getBearerToken().isNotBlank()) }
  var corsOrigins by remember { mutableStateOf(serverViewModel.getCorsAllowedOrigins()) }
  var clientIpPolicy by remember { mutableStateOf(serverViewModel.getClientIpPolicyConfig()) }
  var showRequestTypes by remember { mutableStateOf(serverViewModel.isShowRequestTypes()) }
  var showAdvancedMetrics by remember { mutableStateOf(serverViewModel.isShowAdvancedMetrics()) }
  LifecycleEventEffect(Lifecycle.Event.ON_RESUME) {
    authOn = serverViewModel.getBearerToken().isNotBlank()
    corsOrigins = serverViewModel.getCorsAllowedOrigins()
    clientIpPolicy = serverViewModel.getClientIpPolicyConfig()
    showRequestTypes = serverViewModel.isShowRequestTypes()
    showAdvancedMetrics = serverViewModel.isShowAdvancedMetrics()
  }

  var showReloadDialog by remember { mutableStateOf(false) }

  val endpointUrl = bindAddress?.let { "http://${formatHostForUrl(it)}:$port/v1" }

  val avgThroughput = remember(tokensGenerated, uptimeSeconds) {
    if (uptimeSeconds > 0) String.format(Locale.US, "%.1f", tokensGenerated.toDouble() / uptimeSeconds) else "0.0"
  }

  Box(
    modifier = modifier.fillMaxSize(),
    contentAlignment = Alignment.TopCenter,
  ) {
    Column(
      modifier = Modifier
        .widthIn(max = SCREEN_CONTENT_MAX_WIDTH)
        .fillMaxWidth()
        .verticalScroll(rememberScrollState())
        .padding(horizontal = 20.dp, vertical = 16.dp),
      verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
      // Server not running banner
      if (isStopped) {
        Box(
          modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(MaterialTheme.colorScheme.errorContainer.copy(alpha = 0.3f))
            .padding(16.dp),
          contentAlignment = Alignment.Center,
        ) {
          Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Text(
              text = stringResource(R.string.status_server_not_running),
              style = MaterialTheme.typography.titleMedium,
              color = MaterialTheme.colorScheme.onSurface,
              fontWeight = FontWeight.SemiBold,
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
              text = stringResource(R.string.status_server_not_running_hint),
              style = MaterialTheme.typography.bodySmall,
              color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
          }
        }
      }

      // Active model card
      ActiveModelCard(
        status = status,
        modelName = modelName,
        modelSizeBytes = modelSizeBytes,
        activeAccelerator = activeAccelerator,
        thinkingEnabled = thinkingEnabled,
        speculativeDecodingEnabled = speculativeDecodingEnabled,
        modelLoadTimeMs = modelLoadTimeMs,
        isIdleUnloaded = isIdleUnloaded,
        loadingElapsedSeconds = loadingElapsedSeconds,
        lastError = lastError,
        onReloadClick = { showReloadDialog = true },
      )

      // Endpoint card
      ActiveEndpointCard(
        endpointUrl = endpointUrl,
        isStopped = isStopped,
        corsOrigins = corsOrigins,
        authOn = authOn,
        clientIpPolicy = clientIpPolicy,
        isLoopbackOnly = isLoopbackOnly,
      )

      // Metrics grid
      StatusMetricsGrid(
        uptimeSeconds = uptimeSeconds,
        requestCount = requestCount,
        tokensIn = tokensIn,
        tokensGenerated = tokensGenerated,
        lastDecodeSpeed = lastDecodeSpeed,
        peakDecodeSpeed = peakDecodeSpeed,
        lastTtfbMs = lastTtfbMs,
        avgTtfbMs = avgTtfbMs,
        errorCount = errorCount,
        showRequestTypes = showRequestTypes,
        textRequests = textRequests,
        imageRequests = imageRequests,
        audioRequests = audioRequests,
        showAdvancedMetrics = showAdvancedMetrics,
        lastPrefillSpeed = lastPrefillSpeed,
        avgThroughput = avgThroughput,
        lastItlMs = lastItlMs,
        lastLatencyMs = lastLatencyMs,
        avgLatencyMs = avgLatencyMs,
        peakLatencyMs = peakLatencyMs,
      )
    }
  }

  if (showReloadDialog) {
    ReloadModelConfirmDialog(
      modelName = modelName,
      onConfirm = {
        showReloadDialog = false
        onReloadModel()
      },
      onDismiss = { showReloadDialog = false },
    )
  }
}
